### ISSUE TITLE
アカウントカード

### ISSUE THREAD

**Issue by AyumuAkimoto** [cuculus-dev/cuculus#12]
## 概要
投稿カードの作成

## 画面イメージ

![無題](https://github.com/cuculus-dev/cuculus/assets/107457404/fbe451ca-fcba-41d6-a120-9f12d5aad390)

https://www.figma.com/file/9RPhLdOV35a7bpLy5G44GD/cuculus_wf?type=design&t=p75gWpoqCp9ZZxHA-6

## やること

- [x] ユーザーアイコンの表示
- [x] 背景画像の表示
- [x] ユーザー名の表示
- [x] ＩＤの表示
- [x] bioの表示
- [x] フォローフォロワー数の表示
- [x] フォローボタンの表示（他人アカウントのみ）
- [x] #21
- [x] DMボタンの表示（他人のみ優先度低めなので今はやらなくていい）

**Comment by furutani-k** [comment]
とりあえず今できてるところ。
[Screencast from 2023年09月16日 13時17分35秒.webm](https://github.com/cuculus-dev/cuculus/assets/141975947/cb16f887-a3ef-44d2-8197-486b83501bfb)

#20, #21 のクローズ後に、(mainに更新があれば)rebaseしなおしてからpushしようと思ってます。

**Comment by takecchi** [comment]
> @AyumuAkimoto
> 
> モック画像はpublicに配置すればいいですか？ タグにbase64で埋め込んでおけばいいですか？
> 
> ![image](https://user-images.githubusercontent.com/141975947/268022820-65c3fc96-1f42-4915-9526-02d7346b4180.png)

@furutani-k CC: @AyumuAkimoto 
そしたら`/public`配下に`mock`みたいなディレクトリ切ってそこに画像ファイルを置くようにしましょうか。  
デフォルトの画像みたいなのが別途必要だと思っていて、デフォルトの画像が決まったらその時パス決める感じにしましょう。

**Comment by takecchi** [comment]
## ここで話す内容ではないけども
わざわざ動画付けて貰ってるの申し訳ない（めっちゃ助かります！）...
Vercelに自動デプロイしてプレビューリンクくっつくようにしたいですね
