### ISSUE TITLE
iOS Safariのセーフエリア問題

### ISSUE THREAD

**Issue by takecchi** [cuculus-dev/cuculus#127]
## 関連Issue
(無ければ空)

## 概要
iPhoneは画面の上下に使用できない箇所があるため、専用の対応が必要。
https://useyourloaf.com/blog/iphone-14-screen-sizes/

### 対象ブラウザ
- iOS Safari
- iOS Chrome

### 参考
https://github.com/cuculus-dev/cuculus/pull/121#issuecomment-1849597587

### 補足
一応、`safe-area-inset-bottom`を使用して被らないようにしてはいるものの、
色んな場所でセーフエリアの設定を気にするのは手間かつ対応が漏れる可能性が高い。

理想としては根本的な対策(例えばhtml要素にくっつけるとか)が望ましいが、
`100vh`を使用している箇所も多いのでなかなか難しそう。

テーマにデフォルト値で用意してあげるのが良い？
この際なのでリファクタリングも兼ねてやり方から検討する。

また、実機で試したところ画面が上に埋まるのに`safe-area-inset-top`が0pxだったりする。助けて...

## Todo
- [ ] やることリスト

**Comment by takecchi** [comment]
iOS端末でユーザーページを表示した時にヘッダの上に一瞬隙間が発生するのもこれが原因…？
それともvirtua？

**Comment by takecchi** [comment]
Dialog fullscreenだと上が見切れることはないのでなんとなくわかった気がする

**Comment by so-asano** [comment]
@takecchi 

https://github.com/cuculus-dev/cuculus/blob/c9eb21bc8f9cc15c196bb5ff67f491fe9648610e/src/app/(menu)/(public)/%5Busername%5D/_components/layouts/ProfileSettingModal.tsx#L44

ここを `100svh` とかにすると直るかもしれません（dvh でもいいのかも）。

**Comment by takecchi** [comment]
@so-asano `100dvh`で対応できました😭
ありがとうございます！
