### ISSUE TITLE
・・・ボタンの表示（なんか色々するやつ） 丸いアイコンボタンの作成

### ISSUE THREAD

**Issue by furutani-k** [cuculus-dev/cuculus#21]
MUIデフォルトのIconButtonだと、variant(containedとかoutlined)が使えない。

#20 同様の流れで独自のコンポーネントは作れるが、どうも通常のButtonと高さが違うらしい。
![image](https://github.com/cuculus-dev/cuculus/assets/141975947/879ee6f9-4d09-40ba-bd12-6c8741d34e9c)

あとcolorプロパティをそのまま渡すと透明度がないっぽい？

### 必要な対応
- [x] ~~colorの透明度設定~~ \
      → あとからテーマで色指定
- [x] 高さの調整
    - [x] themeに吐き出すか、コンポーネントにベタ書きするか決定 \
          → とりあえずコンポーネントにベタ書き
    - [x] px指定で調整してしまって問題ないか確認 \
          → とりあえずpx指定

**Comment by takecchi** [comment]
> 通常のButtonと高さが違うらしい

本当だ...これ微妙に不便ですね。Buttonで実装しろってことなのかな
一旦コンポーネントにベタ書きして`// FIXME {内容}`みたいに書いて進めちゃって大丈夫です！

**Comment by furutani-k** [comment]
@takecchi

Buttonでも結局ベタ書きになりそうだったので、元からアイコン用になってるIconButtonで進めておきます。
[DevToolsでスタイル弄って検証](https://github.com/cuculus-dev/cuculus/assets/141975947/b0de9eb7-7730-40c2-a63d-631d92104131)
