### ISSUE TITLE
【デザイン】ワイヤフレームの作成

### ISSUE THREAD

**Issue by AyumuAkimoto** [cuculus-dev/cuculus#3]
## Community Issue
cuculus-dev/cuculus-community/issues/7

## 概要
先行して実装する本アプリ向けで各ページのワイヤフレームをつくる

実装予定の機能
- ログイン/ログアウト
- つぶやき
- タイムライン
- プロフィール
- お気に入り

[figmaリンク](https://www.figma.com/file/9RPhLdOV35a7bpLy5G44GD/cuculus_wf?type=design&node-id=0%3A1&mode=design&t=2lKGkTvSShacoDKs-1
## Todo)

- [ ] /home
- [ ] /[username]
- [ ] /[username]/favorites
- [ ] /settings
- [ ] /signup
- [ ] /login
- [ ] /logout
- [ ] /invitations

一旦１Phaseで実装予定っぽい機能が抑えられるページをリストアップしたけど足りなかったら足しといて。

**Comment by takecchi** [comment]
/signup なら /signin じゃない？って思ったけど、某SNSがそうなのか笑
こっちもそれで行きましょ

**Comment by takecchi** [comment]
@AyumuAkimoto 
つぶやきのコンポーネント
- [ ] モーダルで開かれたときのデザイン
- [ ] タイムラインの上にあるデザイン

**Comment by AyumuAkimoto** [comment]
@takecchi 
招待コード発行画面のパス決まってたらこのチケットのチェックボックス足しといて

**Comment by takecchi** [comment]
@AyumuAkimoto `/invitations`とかでいいかな...追加しました～

**Comment by takecchi** [comment]
一旦ひと段落ついたのでクローズします
