### ISSUE TITLE
投稿フォーム

### ISSUE THREAD

**Issue by takecchi** [cuculus-dev/cuculus#33]
## Community Issue
https://github.com/cuculus-dev/cuculus-community/issues/12

## 概要
- タイムラインの上に表示される投稿フォーム
- モーダルで出てくるタイプの投稿フォーム

**Comment by furutani-k** [comment]
@takecchi 

XのTLの先頭のやつ、いつの間にかモーダルに変わってますけどこっちはどうしましょう？
一応コンポーネントは切り分けてあるので、両方作ってもそこまでカオスにはならないと思いますが

**Comment by furutani-k** [comment]
## 残件
- 投稿API呼ぶと401になるので対応 ← @takecchi 
- モバイルのデザイン(そもそもMUIのInput使うかどうか検討) ← @furutani-k

**Comment by takecchi** [comment]
#112 に移動するためクローズ
