### ISSUE TITLE
ログイン画面のメールアドレスを入力の文言がおかしい

### ISSUE THREAD

**Issue by AyumuAkimoto** [cuculus-dev/cuculus#331]
## 概要
「ユーザー名を入力する」とあるが実際はメールアドレスで入る必要があるので表記がおかしい
メールアドレス・ユーザー名両方でログインできると良さそう
メールアドレスでのログインはバックエンド側の改修も必要

## Todo
- [x] 文言を変更する
- [ ] メールアドレスでログインができる
- [x] ユーザー名でログインができる
- [ ] （bk）メールアドレスでのログイン機能

**Comment by takecchi** [comment]
一旦文言を変更。

あとでメールアドレスorユーザー名でログインできるようにバックエンド側に改修を加え、
フロントエンドの文言もそれに伴って修正する

**Comment by takecchi** [comment]
メールアドレスでもログインできるようにしたのでクローズ
