### ISSUE TITLE
post compornentのレイアウト修正

### ISSUE THREAD

**Issue by AyumuAkimoto** [cuculus-dev/cuculus#63]
## 関連Issue
(無ければ空)

## 概要
投稿者名など文字数が多すぎた場合にレイアウトが崩れる不具合を修正
![無題](https://github.com/cuculus-dev/cuculus/assets/107457404/a1acfb68-8632-4efa-bf9f-5ec0c392dcb8)

## Todo
- [ ] ユーザー名に表示数制限を付ける
- [ ] 超過する場合は…で省略
- [ ] IDが崩れていない
- [ ] 投稿時間表示が崩れていない
- [ ]

**Comment by takecchi** [comment]
Postコンポーネントの横幅最小値は600px(たしか)と決まっていたので、
表示名の要素のmax-widthを合わせるのが良いと思います。

...の表示省略は`text-overflow: ellipsis;`で可能
https://developer.mozilla.org/ja/docs/Web/CSS/text-overflow
