### ISSUE TITLE
ホームタイムラインページ(/home)の作成

### ISSUE THREAD

**Issue by AyumuAkimoto** [cuculus-dev/cuculus#7]
## Community Issue
cuculus-dev/cuculus-community#{issue番号}

## 概要
`/home`
非ログインだった場合は、トップ`/`にリダイレクトされる。

トップページとそこに内包されるコンポーネントを小課題として下記に記載します。
デザインの構成的には基本3カラム構成。

- #8
投稿ボタンや他ページへのリンク（ホーム、アカウント、通知、設定他）が並ぶ想定

- #9
トップページであれば主に投稿カードが時系列で並ぶカラム

- #10
現状空欄でいいのでスペースだけ作っておいておく想定
今後トレンドワードや広告などのスペースとして活用したい

## Todo
- [x] #8
- #9
  - [ ] #32
    - [ ] #33
    - [x] #11
- [x] 未ログインの場合はトップ(/)に戻す

## 動作確認項目
- [ ] フォロー0の状態でホームを開くと何も表示されない
- [ ] フォロー後にページ内遷移して/homeに飛ぶと表示されていること

**Comment by takecchi** [comment]
カラム3分割するレイアウトはアカウントカードRVするにあたり早めに実装必要そうなので実装します。

**Comment by takecchi** [comment]
子チケットで管理するためクローズ
