### ISSUE TITLE
centerColumn

### ISSUE THREAD

**Issue by AyumuAkimoto** [cuculus-dev/cuculus#9]
## Community Issue
https://github.com/cuculus-dev/cuculus-community/issues/12

## 概要
各ページで必要なコンポーネントを呼び出せるような構造だとよいかも？どう？

- /home
投稿フォーム
投稿カード

- /[username]
アカウントカード
投稿カード

- /notifications
通知カード

- /settings
設定フォーム

## Todo
- [ ] #32
  - [ ] #33
  - [x] #11
- [x] #12
- [ ] #82
- [ ] #13

**Comment by takecchi** [comment]
子タスクで管理する為クローズ
